source = source/hyprcolors.conf


background {
    monitor =
    path = /home/turtley/Pictures/wallpapers/.lock
    color = rgb($dark)
    blur_passes = 2
    blur_size = 10
}

label {
    monitor = 
    text = cmd[update:1000] echo "<b>$(date +%H:%M)</b>"
    font_size = 100
    font_family = JetBrainsMono Nerd Font
    color = rgb($fg)
    position = 0, 120
}

label {
    monitor = 
    text = cmd[update:1000] echo "<b>$(date +'%A, %b %d %Y')</b>"
    font_size = 17
    font_family = JetBrainsMono Nerd Font
    color = rgb($fg)
    position = 0, 0
}

input-field {
    monitor = 
    size = 270, 60
    position = 0, -100
    outline_thickness = 3
    outer_color = rgb($mid)
    inner_color = rgb($dark)
    font_color = rgb($fg)
    check_color = rgb($purple)
    capslock_color = rgb($light)
    fail_color = rgb($red)
    fail_text = <b>Nope.</b>
    placeholder_text = <b>Password</b>
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    rounding = 10
}
