# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Transparent terminals
windowrule = opacity 0.85 0.75 0.85, match:class kitty
windowrule = opacity 0.85 0.75 0.85, match:class foot
windowrule = opacity 0.85 0.75 0.85, match:class Alacritty

# No bars for some windows
#windowrule = hyprbars:no_bar on, match:class firefox
#windowrule = hyprbars:no_bar on, match:class codium

# Normal pop-ups
windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.6), match:class ^xdg-desktop-portal-gtk$

# Blurry layers
layerrule = blur on, match:namespace rofi
#layerrule = blur on, match:namespace waybar
