plugin {
    hyprbars {
        enabled = false
        bar_height = 26
        bar_blur = true
        bar_color = rgb($dark)
        col.text = rgb($fg)
        bar_text_font = 'JetBrainsMono Nerd Font'
        bar_text_size = 13
	hyprbars-button = rgb($yellow), 13, , hyprctl dispatch movetoworetoworkspace special:minimized
	hyprbars-button = rgb($green), 13, , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb($red), 13, , hyprctl dispatch killactive
        icon_on_hover = true
        on_double_click = hyprctl dispatch fullscreen
    }

    hyprfocus {
        mode = slide
        bounce_strength = 0.98
        fade_opacity = 0.825
        slide_height = 5
    }

    hyprexpo {
        columns = 3
        gap_size = 3
        bg_col = rgb($dark)
        skip_empty = true
        workspace_method = 'center'
    }

    dynamic-cursors {
        mode = stretch
    }
}
